# Generated by Django 5.1.6 on 2025-03-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparing", "กำลังเตรียมสินค้า"),
                    ("ready", "พร้อมรับสินค้า"),
                    ("completed", "สำเร็จ"),
                    ("cancelled", "ยกเลิก"),
                ],
                default="preparing",
                max_length=20,
            ),
        ),
    ]
